<?php

namespace App\Repositories;

use App\Book;
use App\BookClient;
use Illuminate\Support\Facades\Log;

/**
 * Class BookClientRepository
 * @package App\Repositories
 */
class BookClientRepository extends CrudRepository
{
    /**
     * BookClientRepository constructor.
     * @param BookClient $bookClient
     */
    public function __construct(BookClient $bookClient)
    {
        parent::__construct($bookClient);
    }

    public function store(array $data)
    {
        $book = Book::whereDoesntHave('clients',function ($q){
            $q->whereNull('returned_at');
        })->where('id', $data['book_id'])->first();
        if ($book) {
            $data['borrowed_at'] = now();
            return parent::store($data); // TODO: Change the autogenerated stub
        }

        return new \Exception('book already borrowed');
    }

    public function update(array $pks, array $data)
    {
        $data['returned_at'] = date("Y-m-d H:m:s");
        $pks = [];
        $pks['client_id'] = $data['client_id'];
        $pks['book_id'] = $data['book_id'];
        return parent::update($pks, $data); // TODO: Change the autogenerated stub
    }
}
